name: Memory Journal

on:
  push:
    branches:
      - main   # запускать при пуше в main
  workflow_dispatch:   # запуск вручную из Actions

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build renderer
        run: npm run build

      - name: Package Electron app
        run: npm run dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.zip
